### ISSUE TITLE
[REQUEST]ajouter le MOODLE de l'upem et le WIMS de l'upem sur le serveur WIMS-lti.u-pem.fr

### ISSUE THREAD

**Issue by magdalena-kobylanski** [PremierLangage/wims-lti#23]
Bonjour, 
Serait-il possible d'ajouter le Moodle de l'upem et le WIMS de l'upem au serveur 
https://wims-lti.u-pem.fr.
Merci d'avance.

**Comment by qcoumes** [comment]
Fait !
