### ISSUE TITLE
[BUG] Problem with users having an apostrophe in the surname

### ISSUE THREAD

**Issue by amato-gianluca** [PremierLangage/wims-lti#43]
**Describe the bug**
When a user in Moodle having an apostrophe in the surname clicks for the first time on a link to a WIMS class, the usernames generated in WIMS-LTI and WIMS differ. As a result, the user cannot access WIMS but gets back an error message like the following one:

`WIMS's server responded with an ERROR: user xxxx not in this class (nnnn)`

For example, for an user named `Gianluca D'Amato`, the username generated in WIMS-LTI is `gd_amato`, while the user generated in WIMS is `gdamato`. Manually changing the username in WIMS or in WIMS-LTI to make them equal fixes the problem.

**To Reproduce**
1. Login to Moodle with an user which has an apostrophe in the surname
2. Click on a link to a WIMS-LTI object
3. See error message `WIMS's server responded with an ERROR: user xxxx not in this class (nnnn)`

**Expected behavior**
The WIMS object should appear

**Comment by qcoumes** [comment]
This is most certainly link to PR #41 .

Is there any resource on how WIMS format its username ?

Another solution would be to check if WIMS' response after the creation of an user contains the generated username and use it instead of keeping the one we sent.

**Comment by amato-gianluca** [comment]
I have no idea if there is any resource on the format of WIMS username. In
any case, just to be on the safe side, would it be possible to remove non
alphabetic characters from surnames instead of replacing it with the
underscore?

--gianluca

**Comment by qcoumes** [comment]
@amato-gianluca can you test if the latest change on the `dev` branch fix the problem ? I don't any Moodle installation at hand right now.

It's only a change of the `wimsapi` dependency (qcoumes/wimsapi#5), so an update of the requirements might be needed after switching to `dev` with `pip3 install -r requirements.txt`. Using `install.sh` should also work. Don't forget to execute these command in your virtual environment if you use one.

**Comment by qcoumes** [comment]
Fixed on 194fb6f7d1019b98059a503ae4ec6d5bb2fce2af.

**Comment by amato-gianluca** [comment]
Sorry for the (very) late reply. I just want to confirm that moving to the new WimsAPI fixes the problem.
