### ISSUE TITLE
[REQUEST] Paramètres d'une classe WIMS par LTI custom

### ISSUE THREAD

**Issue by qcoumes** [PremierLangage/wims-lti#5]
Permettre de préciser certains paramètres de la classe grâce à des paramètres *LTI custom*
* Nombre d'élève (Nombre définie sur *WIMS - LTI* par défaut)
* d'expiration (Date définie sur *WIMS - LTI* par défaut)
* Nom de la classe (Nom du cours du LMS par défaut)
* Nom de l'institution (Institution du LMS par défaut)
* La langue (Langue du LMS par défaut)
* etc...

**Comment by qcoumes** [comment]
Je propose ces paramètres:

* `custom_class_name` - Nom de la classe.
* `custom_class_institution` - Nom de l'institution.
* `custom_class_email` - Email de la classe (et du superviseur).
* `custom_class_lang` - Langue de la classe (en, fr, es, it, etc).
* `custom_class_expiration` - Date d'expiration de la classe(yyyymmdd).
* `custom_class_limit` - Nombre de participant maximum entre 10 et 300.
* `custom_class_level` - Niveaux de la classe (E1, ..., E6, H1, ..., H6, U1, ..., U5, G, R).
* `custom_class_css` - Fichier css (doit existé sur le serveur wims).

**Comment by magdalena-kobylanski** [comment]
-* custom_class_limit : le nombre de participants chez nous à l'upem est supérieur à 300 cette année. Je mettrais entre 50 et le max possible.
-* custom_class_css : qu'entends tu par fichier css (doit exister dans WIMS)? il y en a qui existe, mais doit il avoir des particularités?

**Comment by qcoumes** [comment]
* `custom_class_limit` - Je pensais que 300 était la limite de *WIMS*. Cette limite est de combien du coup ?

* `custom_class_css` - Honnêtement, je ne sais pas bien a quoi cela correspond. C'est un paramètre de [*ADM/RAW*](https://wims.auto.u-psud.fr/wims/wims.cgi?module=adm/raw&job=help) (job `addclass`) qu'il m'est possible de donner à la création de la classse.


Pour la date de création de la classe, c'est pour quelle utilisation ? Juste a titre de stockage ou pour créer la classe à la date donné ?

**Comment by qcoumes** [comment]
D'autres paramètres pour le supervisor:

* `custom_supervisor_username` - Nom d'utilisateur du superviseur
* `custom_supervisor_lastname` - Nom de famille du superviseur
* `custom_supervisor_firstname` - Prénom du superviseur
* `custom_supervisor_email` - Email du superviseur
